# todo

services:
  #PostgreSQL container 
  postgres18:
    image: postgres:18
    container_name: postgres18
    env_file:
      - ./debug.env
    networks:
      - orderapp-network
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/docker

  #OrderService container 
  orderservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orderservice
    restart: unless-stopped
    env_file:
      - ./debug.env
    networks:
      - orderapp-network
    ports:
      - "3000:3000"
    depends_on:
      - postgres18
    command: ["./ordersystem"]  # start your app binary on container run

#Shared network 
networks:
  orderapp-network:
    driver: bridge

#Persistent volume for Postgres 
volumes:
  pgdata: